/* Main.c file generated by New Project wizard
 *
 * Created:   Tue Sep 7 2021
 * Processor: STM32F103C6
 * Compiler:  Keil for ARM
 */

#include <stm32f1xx.h>

#include <keypadScan.h>
#include <lcd_4bits.h>

uint8_t a ;

int main (void)
 { 
        //4 indica Entrada de Alta Impedancia.
    //3 Indica Salida
    //8 Indica Entrada
    
   // CODIGO DE PRUEBA KEYPAD + LCD
   
    RCC->APB2ENR |= 0xFC;        /* Enable clocks for GPIO ports */
    
    //Inicializo los perifericos
    KEYPAD_Init();
    lcd_init();
    
    lcd_string("TESTEANDO HOLA",11);
    
   while (1){ 
	 
	KEYPAD_Scan(&a);	//en la variable 'a' se guarda la tecla leida por teclado
	 delay_us(300);
      
      }
 }   
